# Generated by Django 5.1.6 on 2025-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fotos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion1', models.CharField(max_length=90)),
                ('Descripcion2', models.CharField(max_length=2000)),
                ('imageurl', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=2000)),
                ('Palabra', models.CharField(max_length=2000)),
                ('imageurl', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mifoto',
        ),
    ]
